### ISSUE TITLE
Some actors do not read params field (CassandraActor and GeneratorActor)

### ISSUE THREAD

**Issue by gvr** [coral-streaming/coral#32]
The Cassandra and the Generator actor do not process the params field; instead, the parameters (seeds and keyspace) are directly read from the JSON root, in contrast with all other actors with parameters

**Comment by natbusa** [comment]
I think that Jasper latest pull request solves it.

**Comment by natbusa** [comment]
I have only checked the cassandra actor. 
Any news on the generator actor?

**Comment by jaspervz** [comment]
Solved
